on:
  push:
    branches: [main]    
  pull_request:
    branches: [main]    

  workflow_dispatch:

jobs:  
  test:
    if: github.repository_owner == 'jeevananthank' && github.repository.fork == 'false'
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo success
